package io.github.celosia.sys.battle;

// Types of targeting that skills can employ
public enum Targeting {
    SELF,
    OTHER_1R,
    OTHER_2R,
    OTHER_3R,
    ANY_OTHER,
    OTHER_1R_OR_SELF,
    OTHER_2R_OR_SELF,
    OTHER_3R_OR_SELF,
    ANY_OTHER_OR_SELF,
    OTHERS_2_1R,
    OTHERS_2_2R,
    OTHERS_2_3R,
    OTHERS_2_ANY,
    ALLY_1R,
    ALLY_2R,
    ALLY_3R,
    ANY_ALLY,
    TEAM,
    ALL,
    ALL_OTHERS,
    FIELD,
    FIELD_SIDE,
    ADJACENT,
    SELF_UP_DOWN,
    ACROSS,
    ACROSS_UP_DOWN,
    COLUMN_OF_3_1R,
    COLUMN_OF_3_2R,
    COLUMN_OF_3_3R,
    COLUMN_OF_3_4R;
}
